export const ProjectsItems = [
  {
    image: `/images/karate-team.jpg`,
    alt: `Screenshot from Karate Team desktop website`,
    type: `commercial`,
    title: `Karate-Team`,
    description: `Refreshed website of Karate Team Oborniki. Technologies used in the project were selected for the client's needs. So I used static site generation (Astro) to speed up loading times. For animation I use Framer Motion. The data is downloaded from Dato CMS from where the client can manage the content of the site.`,
    technologies: [
      "Astro",
      "React",
      "JavaScript",
      "Dato CMS",
      "tailwind css",
      "Framer Motion",
      "GraphQL",
    ],
    href: `https://final-karate-team.netlify.app/`,
    github: `https://github.com/JayCodeGitHub/Final-Karate-Team`,
  },
  {
    image: `/images/happy-notes.jpg`,
    alt: `Screenshot from Happy Notes desktop website`,
    type: `Non-commercial`,
    title: `Happy-Notes`,
    description: `Happy Notes is a note-taking app built using Next.js, React, Framer Motion, Tailwind CSS and Redux. It is also integrated with Progressive Web App (PWA) technology. It offers a user-friendly interface for creating and organizing three different types of notes. With local storage integration, the notes are securely stored on the user's device. Smoothly designed with an intuitive layout, Happy Notes increases productivity and streamlines note taking.`,
    technologies: [
      "Next JS",
      "React",
      "Redux",
      "tailwind css",
      "TypeScript",
      "Framer Motion",
    ],
    href: `https://happy-notes-pl.vercel.app/`,
    github: `https://github.com/JayCodeGitHub/happy-notes.pl`,
  },
  {
    image: `/images/clothify.jpg`,
    alt: `Screenshot from Clothify desktop website`,
    type: `Non-commercial`,
    title: `Clothify`,
    description: `Clothify is a clothing store project created for my developer portfolio. The main goal of this project was to understand how to manage application state in React at an advanced level.`,
    technologies: [
      "Next JS",
      "React",
      "TypeScript",
      "Framer Motion",
      "tailwind css",
      "PostgreSQL",
      "Prisma",
    ],
    href: `https://clothify-app.vercel.app/shop`,
    github: `https://github.com/JayCodeGitHub/clothify-2.0`,
  },
  {
    image: "/images/car-dealer.jpg",
    alt: "Screenshot from Car Dealer desktop website",
    type: "Non-commercial",
    title: "Car Dealer website",
    description:
      "I created this project in order to learn Next.js and Material UI technologies. The site features a modern and responsive design, along with various pages such as about, offer and contact. It also includes dynamic routing and server-side rendering for improved performance. This project allowed me to gain valuable experience in front-end development and working with popular web frameworks.",
    technologies: ["Next JS", "React", "TypeScript", "Material UI"],
    github: "https://github.com/JayCodeGitHub/Car-Dealer",
  },
  {
    image: "/images/champion-academy.jpg",
    alt: "Screenshot from Champion Academy desktop website",
    type: "commercial",
    title: "Champion-Academy",
    description:
      "Champion Academy is a local sports club based in Oborniki. They asked me to create their website. Working with the client required me to customize the tools. The client required, that the site should be well positioned and that they should be able to change its content.",
    technologies: ["React", "Gatsby", "Dato CMS", "tailwind css", "GraphQL"],
    github: "https://github.com/JayCodeGitHub/Final-Champion-Academy",
  },
];
