export const ProjectsItems = [
    {
      image: `/images/karate-team.jpg`,
      alt: `Screenshot from Karate Team desktop website`,
      type: `commercial`,
      title: `Karate-Team`,
      description: `Still in progress refreshed website of Karate Team Oborniki. Technologies used in the project were selected for the client's needs. So I used Server Site Rendering to speed up loading times. For animation I used GSAP and ScrollTrigger. The data is downloaded from Dato CMS from where the client can manage the content of the site.`,
      technologies: [
        "React",
        "Gatsby",
        "Dato CMS",
        "styled-components",
        "GraphQL",
      ],
      href: `https://karate-team.netlify.app/`,
      github: `https://github.com/JayCodeGitHub/karate-team.pl`,
    },
    {
      image: `/images/happy-notes.jpg`,
      alt: `Screenshot from Happy Notes desktop website`,
      type: `Non-commercial`,
      title: `Happy-Notes`,
      description: `Happy Notes 2.0 is base on Next.js new version of application for creating notes in three different categories. The application has a login system, each user has their own notes. The notes are stored in a database and are uploaded via rest api. I decided to use:`,
      technologies: [
        "Next JS",
        "React",
        "Redux",
        "tailwind css",
        "TypeScript",
        "Mongo DB",
        "JWT",
        "Framer Motion",
      ],
      href: `https://happy-notes.pl/`,
      github: `https://github.com/JayCodeGitHub/Happy-Notes-2.0`,
    },
    {
      image: `/images/clothify.jpg`,
      alt: `Screenshot from Clothify desktop website`,
      type: `Non-commercial`,
      title: `Clothify`,
      description: `Clothify is a clothing store project created for my developer portfolio. The main goal of this project was to understand how to manage application state in React at an advanced level.`,
      technologies: [
        "Next JS",
        "React",
        "TypeScript",
        "Framer Motion",
        "styled-components",
      ],
      href: `https://clothify-app.vercel.app/`,
      github: `https://github.com/JayCodeGitHub/Clothify`,
    },
    {
      image: '/images/car-dealer.jpg',
      alt: 'Screenshot from Car Dealer desktop website',
      type: 'Non-commercial',
      title: 'Car Dealer website',
      description:
      'I created this project in order to learn Next.js and Material UI technologies. The site features a modern and responsive design, along with various pages such as about, offer and contact. It also includes dynamic routing and server-side rendering for improved performance. This project allowed me to gain valuable experience in front-end development and working with popular web frameworks.',
      technologies: ['Next JS', 'React', 'TypeScript', 'Material UI'],
      href: 'https://car-dealer-ten.vercel.app/',
      github: 'https://github.com/JayCodeGitHub/Car-Dealer',
    },
    {
      image: '/images/champion-academy.jpg',
      alt: 'Screenshot from Champion Academy desktop website',
      type: 'commercial',
      name: 'Champion-Academy',
      description:
      'Champion Academy is a local sports club based in Oborniki. They asked me to create their website. Working with the client required me to customize the tools. The client required, that the site should be well positioned and that they should be able to change its content.',
      technologies: ['React', 'Gatsby', 'Dato CMS', 'tailwind css', 'GraphQL'],
      href: 'https://championacademy.pl/',
      github: 'https://github.com/JayCodeGitHub/Final-Champion-Academy',
    },
  ];